# Generated by Django 2.2.5 on 2020-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCodeCallbacksUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkid', models.CharField(blank=True, max_length=200, null=True)),
                ('Text', models.CharField(blank=True, max_length=200, null=True)),
                ('to', models.IntegerField(default=0)),
                ('From', models.IntegerField(default=0)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
