# Generated by Django 2.2.5 on 2020-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_shortcodecallbacksurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=15, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
