# Generated by Django 2.2.5 on 2020-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_grantapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=500)),
                ('Email', models.EmailField(max_length=50)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
