# Generated by Django 2.2.5 on 2020-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200122_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='amount',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='amount_dispensed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='amount_request',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
